
sudo: required

services:
  - docker

script:
    - docker build -t $DOCKER_USERNAME/ss .
    - docker run -d -p 127.0.0.1:8388:8388 --name ss $DOCKER_USERNAME/ss
    - docker ps | grep -q ss


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push fredliang/ss;
    docker push fredliang/ss;
    fi
